### PR TITLE
updates to environment sdk constraints and related dependency updates

### PR DESCRIPTION
**Pull request by KevinTheGray**
This is an update for recent updates to the dart sdk, as well as updates to dependencies that have made the same change

### CODE REVIEW

**Comment by KevinTheGray** [comment]
@MikeMitterer this is related to this pull request: https://github.com/MikeMitterer/dart-latlong/pull/5/files, while also maintaining the constraint. 

I also ran the tests and they are all passing.  this required some version updates to the dev dependencies

**Comment by diegoveloper** [comment]
any news about this PR ?

**Comment by KevinTheGray** [comment]
@diegoveloper haven't heard anything myself, have just been using my fork for now

**Comment by diegoveloper** [comment]
Ok, I'm using your fork too. Is it ok? Thanks

**Comment by KevinTheGray** [comment]
yes, of course!  it is exactly the same as `0.5.3`, just with the updated constraints

**Comment by diegoveloper** [comment]
yes, I saw the changes. Thanks

**Comment by MikeMitterer** [comment]
Thanks. Update is on the way to pub...

**Pull request closed without merging**
